package ChatApplication;

/**
 *
 * @author Shameel Shajaad
 */
public class SenderWindow extends javax.swing.JFrame {

    /**
     * Creates new form SenderWindow
     */
    public SenderWindow(String senderName) {
        initComponents();
        this.setTitle(senderName);
        this.lblSenderName.setText(senderName);
        ChatManager.addWindow(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSenderName = new javax.swing.JLabel();
        jTextFieldMessage = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        jButtonAddSender = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jTextMessageArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSenderName.setBackground(new java.awt.Color(153, 153, 255));
        lblSenderName.setFont(new java.awt.Font("Segoe UI", 1, 52)); // NOI18N
        lblSenderName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSenderName.setText("ADD SENDER");
        lblSenderName.setOpaque(true);

        jTextFieldMessage.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSend.setText("SEND");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        jButtonAddSender.setBackground(new java.awt.Color(153, 153, 255));
        jButtonAddSender.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButtonAddSender.setText("+");
        jButtonAddSender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSenderActionPerformed(evt);
            }
        });

        jTextMessageArea.setEditable(false);
        jTextMessageArea.setColumns(20);
        jTextMessageArea.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jTextMessageArea.setLineWrap(true);
        jTextMessageArea.setRows(5);
        jScrollPane.setViewportView(jTextMessageArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSenderName, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddSender, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSenderName, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(jButtonAddSender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jTextFieldMessage))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddSenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSenderActionPerformed
        new AddSenderForm().setVisible(true);
    }//GEN-LAST:event_jButtonAddSenderActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        String msg=jTextFieldMessage.getText();
        
        if(!msg.isEmpty()){
            Sender sender=new Sender(lblSenderName.getText());
            String senderName=lblSenderName.getText();
            String message=sender.message(msg);
            
            ChatManager.setMessage(senderName,message);
            
            jTextFieldMessage.setText("");
        }
    }//GEN-LAST:event_btnSendActionPerformed

    public void receiveMessage(String senderName,String msg){
        if(senderName.equals(lblSenderName.getText())){
            jTextMessageArea.append("Me: "+msg+"\n");
        }else{
            jTextMessageArea.append(senderName+": "+msg+"\n");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SenderWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SenderWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SenderWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SenderWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JButton jButtonAddSender;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField jTextFieldMessage;
    private javax.swing.JTextArea jTextMessageArea;
    private javax.swing.JLabel lblSenderName;
    // End of variables declaration//GEN-END:variables
}
